#!/usr/bin/env python3
"""Supplementary Figure S3 - independent-cohort validation (combined panels).

Stitches the per-cohort pilot-curve products (QinJ_2012, YachidaS_2019;
produced by scripts/run_validation_pilot_sensitivity.py runs documented in
validation_datasets/results/) into one 2x2 figure: rows are cohorts,
columns are observed-size consistency (eval n = 20) and extrapolation
(eval n = 80).

If an archived ``sensitivity_pilot_curves.png`` is missing (e.g. a release
checkout without the archived results), it is first regenerated by re-running
the documented full validation pipeline for that cohort (see the cohort's
README.md); a notice is printed because that re-run is the full production
computation and can take hours (and needs the QIIME 2 env).
"""
from pathlib import Path
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SRC_A = ROOT / "validation_datasets" / "results" / "QinJ_2012_core_matched" / "sensitivity_pilot_curves.png"
SRC_B = ROOT / "validation_datasets" / "results" / "YachidaS_2019_core_matched" / "sensitivity_pilot_curves.png"
OUT = ROOT / "figures" / "output"

QIIME_PY = Path("/opt/miniconda3/envs/qiime2-metagenome-2024.10/bin/python")

# (cohort, archived curve image) — the panel sources stitched below.
COHORTS = [("QinJ_2012", SRC_A), ("YachidaS_2019", SRC_B)]


def _recompute_cohort(cohort: str) -> None:
    """Re-run the documented full pilot-sensitivity pipeline for one cohort
    (the reproduction command in validation_datasets/results/<cohort>_core_matched/README.md;
    scripts/run_gene_pilot_sensitivity.py delegates to
    scripts/run_validation_pilot_sensitivity.py unchanged)."""
    py = str(QIIME_PY) if QIIME_PY.exists() else sys.executable
    proc = ROOT / "validation_datasets" / "processed" / cohort
    cmd = [
        py, str(ROOT / "scripts" / "run_gene_pilot_sensitivity.py"),
        "--workflow", "gene",
        "--gene-table", str(proc / "table.csv"),
        "--gene-taxonomy", str(proc / "taxonomy.csv"),
        "--gene-tree", str(proc / "rooted-tree.nwk"),
        "--gene-group", str(proc / "group.csv"),
        "--gene-pilot-ns", "7,10,20",
        "--gene-eval-observed", "20",
        "--gene-eval-ns", "20,80",
        "--eval-extrapolate", "80",
        "--gene-grid", "auto",
        "--gene-power-points", "12",
        "--gene-near-zero-points", "4",
        "--gene-pi-candidates", "17",
        "--gene-scale-candidates", "6",
        "--pool-size-per-group", "180",
        "--boot-number", "200",
        "--permutations", "199",
        "--target-omega2", "0.03",
        "--target-power", "0.8",
        "--scenario-n-jobs", "2",
        "--random-seed", "20260614",
        "--out", str(ROOT / "validation_datasets" / "results" / f"{cohort}_core_matched"),
    ]
    subprocess.run(cmd, cwd=ROOT, check=True)


def main() -> None:
    missing = [(cohort, src) for cohort, src in COHORTS if not src.exists()]
    if missing:
        # Fallback: the release ships no archived results, so regenerate the
        # missing per-cohort curve images instead of dying with
        # FileNotFoundError. This is the full production validation pipeline.
        print(
            f"[suppfig3] archived data not found ({', '.join(str(s) for _, s in missing)}); "
            "recomputing from scratch via scripts/run_gene_pilot_sensitivity.py "
            "(this is the FULL validation pipeline and can take hours; needs the "
            "QIIME 2 env) ...",
            flush=True,
        )
        for cohort, _ in missing:
            print(f"[suppfig3] recomputing {cohort} ...", flush=True)
            _recompute_cohort(cohort)
        still_missing = [str(src) for _, src in COHORTS if not src.exists()]
        if still_missing:
            raise SystemExit(
                "[suppfig3] recompute finished, but these panel sources are still missing:\n  "
                + "\n  ".join(still_missing)
            )
    q = Image.open(SRC_A)
    y = Image.open(SRC_B)
    W, rowh = q.size
    label_h, gap = 90, 30
    canvas = Image.new("RGB", (W, label_h * 2 + rowh * 2 + gap), "white")
    draw = ImageDraw.Draw(canvas)
    font = None
    for fp in ("/System/Library/Fonts/Supplemental/Arial Bold.ttf", "/System/Library/Fonts/Supplemental/Arial.ttf"):
        try:
            font = ImageFont.truetype(fp, 44)
            break
        except Exception:
            pass
    rows = [("a", "QinJ_2012 (T2D vs control)", q), ("c", "YachidaS_2019 (CRC vs control)", y)]
    yoff = 0
    for letter, title, img in rows:
        draw.text((10, yoff + 18), letter, fill="black", font=font)
        draw.text((W // 2 - 700, yoff + 18), title, fill="black", font=font)
        draw.text((W // 2 + 10, yoff + 18), "b" if letter == "a" else "d", fill="black", font=font)
        canvas.paste(img, (0, yoff + label_h))
        yoff += label_h + rowh + gap
    canvas.save(OUT / "suppfig3_independent_cohorts.png", dpi=(320, 320))
    # PDF export via matplotlib (PIL's PDF plugin needs JPEG support)
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    arr = np.asarray(canvas)
    h, w = arr.shape[:2]
    fig = plt.figure(figsize=(w / 320, h / 320), dpi=320)
    fig.add_axes([0, 0, 1, 1]).imshow(arr)
    plt.axis("off")
    fig.savefig(OUT / "suppfig3_independent_cohorts.pdf")
    plt.close(fig)
    print(OUT / "suppfig3_independent_cohorts.png")


if __name__ == "__main__":
    main()
